/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mbixwvsrjrqlzzdiuptw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iaXh3dnNyanJxbHp6ZGl1cHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTgwNzQsImV4cCI6MjA3NDI3NDA3NH0.UaqDDuwWMJsFd-CBHdI1cV4EZe3HSYcWNiyu0X-5KRA"